### ISSUE TITLE
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value'

### ISSUE THREAD

**Issue by gms8994** [vorot93/boinc-rpc-rs#1]
When using the examples provided within `src/lib.rs`

```
tokio::runtime::Runtime::new().unwrap().block_on(async {
    let transport = boinc_rpc::Transport::new("127.0.0.1:31416", Some("1033644eaad1ea7d91bc48a749f1620b"));
    let mut client = boinc_rpc::Client::new(transport);

    println!("{:?}\n", client.get_messages(0).await.unwrap());
    println!("{:?}\n", client.get_projects().await.unwrap());
    println!("{:?}\n", client.get_account_manager_info().await.unwrap());
    println!("{:?}\n", client.exchange_versions(&boinc_rpc::models::VersionInfo::default()).await.unwrap());
    println!("{:?}\n", client.get_results(false).await.unwrap());
})
```

I get a panic:

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /Users/gms8994/.cargo/git/checkouts/rust-boinc-rpc-cf23ed20e457ad15/65e00a8/src/lib.rs:313:34
```

I can run any single call correctly; is there some bug with keeping track of the state of the connection?

**Comment by azvast** [comment]
Hello @vorot93
Thanks for this library.

I am going to use this library for BOINC client, but got this error at start.

```
Starting BOINC Client...
thread 'main' panicked at 'internal error: entered unreachable code', D:\Boid\Current\Boid_Desktop\Github_Samples\rust-boinc\rust-boinc-rpc\src\lib.rs:340:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\debug\boinc-client.exe` (exit code: 101)
```

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', D:\Boid\Current\Boid_Desktop\Github_Samples\rust-boinc\rust-boinc-rpc\src\lib.rs:313:43
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\debug\boinc-client.exe` (exit code: 101)
```
I used `tokio = { version = "0.2", features = ["macros"] }`.

![image](https://user-images.githubusercontent.com/83703580/159122197-ad4048b9-438a-4ec6-acbe-651d2edf61b3.png)

I don't know how I can fix this error, I would like you to help me.

Thanks again!
